### ISSUE TITLE
Directory picking with persistent permission and traversing picked directory 

### ISSUE THREAD

**Issue by canewsin** [chaudharydeepanshu/pick_or_save#2]
Use case: want to access to specific directory via storage access framework (SAF) and persist the "use this folder" permission across reboots. once user grants permission, list files on flutter side.

I just hop into this via some issue page, want to know if such use case is supported via this package.

**Comment by chaudharydeepanshu** [comment]
Thank you for your suggestion, but sadly the use case is not supported at this time. However, I believe it would be simple to implement.

Currently, the multiple file saving provides an option to select a folder for saving various files using the SAF `ACTION_OPEN_DOCUMENT_TREE`. So, it would be easy to upgrade the plugin functionality to support picking a folder with persistent permission(by adding flags) so that we can then access its content even after rebooting.

I'm somewhat busy, but I will **try to implement it by this week**. 

Also, I'm attaching an image in which you might be interested in your use case:-
![image](https://user-images.githubusercontent.com/85361211/202923549-42d2c662-3610-4a89-925d-6dd1c63f5f39.png)

Let me know if you have any further questions or suggestions.

**Comment by canewsin** [comment]
@chaudharydeepanshu 
I am aware this Caution on SS.
Thanks for your initial work as well, 'cause scoped storage is incompatible with `data:io`'s File access even with proper permissions, eagerly waiting for your impl.
Nice work too on your other repos.

**Comment by chaudharydeepanshu** [comment]
@canewsin Thanks for appreciating my work and I'm glad you liked that.

I have started working on this now. But I need a little more info from you :
-  Can you tell me how you will be using this use case, like how you will be using the files from selected the directory.

This info will help me better understand your requirements to provide a much more suitable solution.

Currently what I have in my mind is something like this:
- Allow the user to pick a folder on android and then pass the URI of the picked folder back to flutter.
- Then use the directory URI to fetch the URI of all the files or sub-directories inside this chosen directory.
- Then either uses the current method to get the data of a file from URI to flutter or maybe something else like a stream of data to flutter.

Let me know what you think of it. Also, if you have something else in mind then let me know.

**Comment by canewsin** [comment]
SAF has certain restrictions on which dirs developers allowed to access.
```rust
RootOfStorage/
Android/data/
Android/obb/
```
with these restrictions app started storing their content in `Android/media` dirs, but those can only be accessed by app itself, if we want to access those dirs with user's permission let's say for example pdf viewer, we need to request this permission & persist this for future. 
Permission persistence is possible through this
https://developer.android.com/training/data-storage/shared/documents-files#persist-permissions.
Thus once user grants us permission to media dir or let's say we receive documents via whatsapp we can list all those in a pdf viewer with single user permission using SAF.

**Comment by brightseagit** [comment]
Thanks for that clarification I understood your requirement👍. I will also try to add the above pdf example use case in plugin examples to better understand the implementation.

**Comment by chaudharydeepanshu** [comment]
Just an update:

I have almost completed this new feature so I may post it by latter tomorrow after few teaks and documentation.

This is how it will work:-
- We pick directory (lets pick Android/Media) and this will give us the uri of that directory.
- Then we call a new function with the uri, whose job is to get all the documents inside the picked directory.

  We can also set recurseDirectory to true to that function to get all documents even from the sub directories. But this can take more time depending on number of documents.

  From my testing I found that it will take 26 seconds to go through 17000 files.

- Now after this we save the uri of those directories or files which are important to us so that the next time we don't have to transverse through all the other useless directories and can start the transverse from our own saved uris.

Also, soon I will try to add some other methods like to check if we still have access to a uri or not, or to remove access from it, or an option to stop an ongoing recursion in directory.

**Comment by chaudharydeepanshu** [comment]
@canewsin I have updated the [plugin](https://pub.dev/packages/pick_or_save) with these new features. And I hope that it will be helpful to you and many others.

The documentation for these features can be found [here ](https://web.archive.org/web/20221124211745/https://pub.dev/packages/pick_or_save#picking-directory) and [here](https://web.archive.org/web/20221124211745/https://pub.dev/packages/pick_or_save#operations-on-picked-directory-uri).

The features added are:-
- Support for picking directories with persistent permission and returning its uri.
- Support to optionally transverse through all subdirectories in a picked directory and return their uris.
- Support to selectively transverse starting through a directory whose uri we stored from the previous transverse.
- Support to provide mime types and extensions list when transversing, to only get those types of documents in the result.
- Support for getting all persistent permission uris from the device.
- Support for checking the persistent permission status of uri.
- Support for releasing persistent permission for a uri.

Let me know if you face any issues regarding it.
